"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car != 'ford'? I predict True.");
console.log(car != 'ford');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car !== 'ford'? I predict True.");
console.log(car !== 'ford');
console.log("Is car starts with 'su'? I predict True.");
console.log(car.startsWith('su'));
console.log("Is car ends with 'baru'? I predict True.");
console.log(car.endsWith('baru'));
